export const ADD_FOOD_ITEM_START="ADD_FOOD_ITEM_START";
export const ADD_FOOD_ITEM_SUCCESS="ADD_FOOD_ITEM_SUCCESS";
export const ADD_FOOD_ITEM="ADD_FOOD_ITEM";

export const FETCH_FOOD_ITEM_START='FETCH_FOOD_ITEM_START'
export const FETCH_FOOD_ITEM_SUCCESS='FETCH_FOOD_ITEM_SUCCESS'
export const FETCH_FOOD_ITEMS='FETCH_FOOD_ITEMS'

export const LOGIN_START='LOGIN_START';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAIL='LOGIN_FAIL';

export const VOTE_SUCCESS='VOTE_SUCCESS'